// <autogenerated>
//   This file was generated by T4 code generator CreateIntegrationTestsScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace EnergyTrading.Mdm.Client.IntegrationTests.Checkers
{
    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.Test;

    public class SourceSystemDetailsChecker : Checker<SourceSystemDetails>
    {
        public SourceSystemDetailsChecker()
        {
			            Compare(x => x.Name);
			        }
    }
}
